import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Wholesale</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>Test Wholesale Inc.</h1>

        <p>Buy CBD oil from our collection of high quality CBD products for sale – including CBD oil tinctures, CBD infused gummies, CBD oil capsules, and CBD for sleep in a variety of options. Our CBD products deliver superior hemp extracts with consistent quality.</p>

        <div className={styles.grid}>

        </div>
      </main>


    </div>
  )
}
